name = "search-hub"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"
PLUGINS_BILIBILI_USER_COOKIE = "buvid4=98FCD548-69A9-1455-69CF-6A64B36BC4A000607-024031218-HyYFmR0Ivh2P1Xfp2yjdqg%3D%3D; buvid3=C63D509D-FF05-8A4E-8574-3343C6A9FBD216132infoc; b_nut=1712955316"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

