name: QQStatPlugin Release

on: 
  push:
    tags:
      - 'QQStatPlugin-v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
        
    - name: Build
      run: |
        cd ./plugins/QQStatPlugin
        dotnet build --configuration Release
        ls
        ls ./bin/Release/
        ls ./bin/Release/net6.0/
      
    - name: Zip the Build
      run: |
        cd ./plugins/QQStatPlugin/bin/Release/net6.0
        zip -r QQStatPlugin-net6.0.zip *
        cd ../../../../../
        mv ./plugins/QQStatPlugin/bin/Release/net6.0/*.zip ./

    - name: Create temp-release-note.md
      run: |
        cp utils/generate-release-note.ps1 generate-release-note.ps1
        $env:GitProjectTagName="QQStatPlugin"
        $env:GitProjectPath="plugins/QQStatPlugin/*"
        ./generate-release-note.ps1
      shell: pwsh
      
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        #tag_name: ${{ github.ref }}
        #name: ${{ github.ref }}
        # body: TODO New Release.
        body_path: temp-release-note.md
        draft: false
        prerelease: false
        files: |
          QQStatPlugin-net6.0.zip
          LICENSE 
          README.md